apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
      #nodePort: 30888
      protocol: TCP
  selector:
    app: jupyter
  type: ClusterIP
status:
  loadBalancer: {}
